[package]
authors = ["Ivan Dardi <ivy.dardi@gmail.com>"]
build = "build.rs"
name = "compiler"
version = "0.1.0"
[build-dependencies]
lalrpop = "0.13.1"

[dependencies]
lalrpop-util = "0.13.1"
regex = "0.2.2"
